//go:build !linux

// Package ebpf contains stub types for non-Linux builds.
// On Linux, these are generated by bpf2go from probe.c.
package ebpf

import "github.com/cilium/ebpf"

// probeObjects contains all eBPF objects after they have been loaded.
// This is a stub for non-Linux builds.
type probeObjects struct {
	probePrograms
	probeMaps
}

func (o *probeObjects) Close() error { return nil }

type probePrograms struct {
	TraceTcpSendmsg     *ebpf.Program
	TraceTcpCleanupRbuf *ebpf.Program
}

type probeMaps struct {
	TargetPorts  *ebpf.Map
	PortStatsMap *ebpf.Map
	ConnStatsMap *ebpf.Map
}

// probePmPortStats mirrors the C struct pm_port_stats.
type probePmPortStats struct {
	RxBytes     uint64
	TxBytes     uint64
	RxPackets   uint64
	TxPackets   uint64
	Connections uint64
}

// probePmConnKey mirrors the C struct pm_conn_key.
type probePmConnKey struct {
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

// probePmConnStats mirrors the C struct pm_conn_stats.
type probePmConnStats struct {
	RxBytes      uint64
	TxBytes      uint64
	StartNs      uint64
	LastUpdateNs uint64
}

// loadProbeObjects is a stub that returns an error on non-Linux.
func loadProbeObjects(obj *probeObjects, opts *ebpf.CollectionOptions) error {
	return errNotLinux
}

var errNotLinux = &notLinuxError{}

type notLinuxError struct{}

func (e *notLinuxError) Error() string {
	return "eBPF is only supported on Linux"
}
